### ISSUE TITLE
auto-merge workflow is busted

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10366]
```
Run gh pr merge --auto --merge "$PR_URL"
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
```
