### ISSUE TITLE
UI Guided Tour

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#124]
Would be nice if when DIM is opened for the first time, we had a tour that showed users the features of DIM.  Make it skippable.

It's like the tours you get when you see an arrow, bubble of text, and a 'next' button, or it senses you've completed the action and moves to the next step.

**Comment by phatsk** [comment]
Proposal CSS:

````css
.tour.box {
  background: #eee;
  float:left;
  position:absolute;
  color:#000;
  padding: 1em;
  border-radius: 10px;
  box-shadow: 8px 8px 12px #000;
}

#welcome {
  top: 40px;
  left: 100px
}

.tour.nav {
  color: #00f;
  float:right;
  margin-top:0.5em;
}
````

HTML
````html
<div id="tour">
	<div class="tour box" id="welcome">
		Welcome to Destiny Item Manager!
		<br>
		<span class="tour nav">Next &gt;</span>
	</div>
</div>
````

Rendered:

![screen shot 2015-05-18 at 12 49 06 am](https://cloud.githubusercontent.com/assets/990374/7674519/b80b241a-fcf7-11e4-8605-293912d94ed4.png)

A lot of absolute positioning needed, and not sure how to make it forward-compatible with goals like responsive/mobile (unless we drop those to a quick tutorial instead of a "tour")
