### ISSUE TITLE
Inventory now expands beyond page width

### ISSUE THREAD

**Issue by Empereol** [DestinyItemManager/DIM#2137]
Inventory doesn't respect `Vault maximum inventory width`  anymore and overflows its container causing the window to scroll if you have too many items. See attached image below.

![capture](https://user-images.githubusercontent.com/746530/30483739-f2fd32e6-99f5-11e7-9ce6-dac7fddcc070.PNG)

It seems it's the 
```css
.store-cell.account-wide {
    width: auto;
}
```
is causing the issue.
