### ISSUE TITLE
[Proposal] Shorthand for combining similar search filters

### ISSUE THREAD

**Issue by vivekhnz** [DestinyItemManager/DIM#4008]
A nice-to-have feature for search would be the ability to combine similar filters together succinctly. My proposed syntax would allow users to combine filters with matching prefixes (e.g. `is`, `source` etc.) using boolean operators **&** (and) and **|** (or).

For example:

Current Syntax | Proposed Shorthand
------------ | -------------
`is:hunter is:legendary is:gauntlets` (35 chars) | `is:hunter&legendary&gauntlets` (29 chars)
`source:leviathan or source:eow or source:sos or source:menagerie or source:crownofsorrow` (88 chars) | `source:leviathan\|eow\|sos\|menagerie\|crownofsorrow` (48 chars)
`is:energy is:autorifle or is:submachine` (39 chars) | `is:energy&autorifle\|submachine` (30 chars)

This syntax also enables filters in the form of `(A and B) or C` (provided the A and B constraints use the same prefix), which are not possible using the current filters. For example:

`is:handcannon&kinetic or is:pulserifle`

## Use cases

The main benefit of this feature (IMO) is reducing the length of search queries that contain multiple **or** constraints. The second query in the above table which identifies Calus-themed items can be almost halved using the shorthand syntax.

Another possible use case is identifying items that satisfy particular loadout requirements. For example, suppose the current raid lair **Armsmaster** loadout is:

- Kinetic Auto Rifle
- Energy Sidearm
- Heavy Grenade Launcher

Users can currently identify items that match this loadout using three separate queries:

- `is:kinetic is:autorifle`
- `is:energy is:sidearm`
- `is:heavy is:grenadelauncher`

However these could be expressed in a single query using the following shorthand syntax:

`is:kinetic&autorifle or is:energy&sidearm or is:heavy&grenadelauncher`

## Approach

1. Split search query into terms, generally by whitespace but allow for whitespace inside a term if it is surrounded by single or double quotes
2. For each term that starts with a known prefix (e.g. `is:`, `source:` etc.), split into a key-value pair by the colon
3. For each key-value pair, split the value by the **&** character into a collection of constraint sets. For example, `is:energy&autorifle|submachine&legendary` would yield the following constraint sets:
    - `energy`
    - `autorifle|submachine`
    - `legendary`
4. For each constraint set
    a. Split by the **|** character into a collection of constraints e.g.
        - `energy` -> [`energy`]
        - `autorifle|submachine` -> [`autorifle`, `submachine`]
        - `legendary` -> [`legendary`]
    b. If the set contains a single constraint (no **|**'s), build a filter for the sole constraint
    c. If the set contains more than one constraint (at least one **|**), compose a filter using the **or** predicate
5. For each key-value pair
    a. If the key-value pair has a single constraint set (no **&**'s), return the sole constraint set's filter
    b. If the key-value pair has multiple constraint sets (at least one **&**), compose a filter using a new **and** predicate

For example, given the search query...

`source:leviathan|eow|sos is:kinetic&handcannon|pulserifle or is:shotgun|sniperrifle&energy`

...the following filters would be generated:

```yaml
filters:
  -
    predicate: or
    childFilters:
      - 
        predicate: source
        value: leviathan
      - 
        predicate: source
        value: eow
      - 
        predicate: source
        value: sos
  -
    predicate: or
    childFilters:
      -
        predicate: and
        childFilters:
          - 
            predicate: is
            value: kinetic
          - 
            predicate: or
            childFilters:
              - 
                predicate: is
                value: handcannon
              - 
                predicate: is
                value: pulserifle
      - 
        predicate: and
        childFilters:
          - 
            predicate: or
            childFilters:
              - 
                predicate: is
                value: shotgun
              - 
                predicate: is
                value: sniperrifle
          - 
            predicate: is
            value: energy
```

## Considerations

- To ensure the existing **or** predicates work with the new syntax, we would need to implement a corresponding **and** predicate. We could rename the `orFilters` property to `childFilters` (or something similar) and re-use it for this **and** predicate.
- I am unsure how this syntax should behave with range filters e.g. `stat:impact>X`. Should you be able to combine different stat constraints together e.g. `stat:range>50&stability>70`? Or should this be limited to a single stat e.g. `stat:rpm>110&<180`?
- The search box auto-suggest will need to be modified to suggest values after a **&** or **|** character is entered
- The ampersand (**&**) is generally understood as meaning **AND**, however the pipe character (**|**) is less commonly understood as meaning **OR**. Should we use a different character instead e.g. comma?
