### ISSUE TITLE
Avoid hover emulation

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9335]
Not super easy, especially on multi-pointer devices, but it'd be good to avoid the "last thing you touched is hovered" default behavior on Mobile Safari. See https://react-spectrum.adobe.com/blog/building-a-button-part-2.html

**Comment by liamdebeasi** [comment]
I'd be happy to help out with this. I did some initial investigation, and using one of the hover media queries should yield good results:

```css
button {
  background: red;
}

@media (hover: hover) {
  button: hover {
    background: green;
  }
}
```

`hover: hover` only applies if the primary input mechanism can hover over elements. You do have some flexibility with how strict this is. For example, you could instead use `any-hover: hover` which matches if _any_ input (not just the primary input) can hover over elements.

There are some [gotchas](https://github.com/ionic-team/ionic-framework/issues/18570#issuecomment-1783318394) with certain devices not reporting the correct input type. While this approach will work for most devices, there are a handful of Android devices that may still have the original hover emulation behavior.


------

Manually throwing a bunch of `@media (hover: hover)` into the codebase probably isn't the most maintainable, so I think a Sass mixin would be beneficial here:

```scss
button {
  background: red;

  @include hover {
    background: green;
  }
}
```

While this seems like the ideal solution at a glance, DIM's use case is slightly more complex since it often shares styles between states. For example, the [CollapsibleTitle component shares styles for `hover` and `focus-visible`](https://github.com/DestinyItemManager/DIM/blob/d337a621447c76b46b0b3771fa90e33a3bf84cda/src/app/dim-ui/CollapsibleTitle.m.scss#L39-L40). Using the above mixin would mean duplicating styles in the source code for both hover and focus.

An alternative could be to use a mixin that allows you to mix and match different interactivity states:

```scss
button {
  background: red;

  // could also add support for :focus-within and :active
  @include interactive($hover: true, $focus: true) {
    background: green;
  }
}
```

While the compiled code will still need to duplicate styles because hover is in its own media query, you won't have to duplicate styles in your source code which should help make this easy to maintain.

Here is a [playground that shows the compiled CSS](https://sass-lang.com/playground/#eJx9UMEKgzAMvfcrchjiYDt4dQj9lVqjC6ut1FYGw3/f2ur0sFkINMnLy3spCt7TkzTczYQWXgyA99iQgDxWytQ4xw5AVm648Lg02qF2t5jPLMTM2MLZGunHiM3K+L9ONFKtcJnfT+/n6FO1QjqaMD8tMlqhRrzAKfIsaVLFqYWEgqoCZ/2XnrRUvkE41JyWrzxJ8h+ezc+B99o7Z3RE1UI+Omu8bkroLKIOULYj/GU0LN58hmw9/p5u8HZQuB7uDZ56iKI=?s=L14C1-L15C17). One thing we'd need to figure out is how to handle components that also [use the `.checked` state](https://github.com/DestinyItemManager/DIM/blob/d337a621447c76b46b0b3771fa90e33a3bf84cda/src/app/loadout/ingame/EditInGameLoadout.m.scss#L33-L35). However, the number of times DIM shares styles between pseudo-classes and regular classes is pretty small, so it may not be worth the added effort right now.

Does this approach seem reasonable to you?
